DROP TABLE IF EXISTS person;
DROP TABLE IF EXISTS keyword;
DROP TABLE IF EXISTS journal;
DROP TABLE IF EXISTS "file";
DROP TABLE IF EXISTS association;
DROP TABLE IF EXISTS editorship;
DROP TABLE IF EXISTS authorship;
DROP TABLE IF EXISTS item;
